* QUESTAO 86 - Declare a checkbox and an input field side-by-side inside a frame.

REPORT zabap101_086 .

SELECTION-SCREEN: BEGIN OF BLOCK t001 WITH FRAME .
  SELECTION-SCREEN BEGIN OF LINE .
    POSITION 1.
      PARAMETERS p_check AS CHECKBOX.
    SELECTION-SCREEN COMMENT 3(4) text-001 FOR FIELD p_text.
    POSITION 10.
      PARAMETERS p_text TYPE string.
  SELECTION-SCREEN END OF LINE .
SELECTION-SCREEN: END OF BLOCK t001 .