* QUESTAO 88 - Create a tabbed block with 3 tabs. Each of them should have a different content.

REPORT zabap101_088 .

SELECTION-SCREEN: BEGIN OF SCREEN 1 AS SUBSCREEN.
PARAMETERS: s_n TYPE n LENGTH 5,
            s_i TYPE i.

SELECTION-SCREEN: END OF SCREEN 1 .

SELECTION-SCREEN: BEGIN OF SCREEN 2 AS SUBSCREEN.
PARAMETERS: s_c TYPE c LENGTH 15,
            s_s TYPE string.

SELECTION-SCREEN: END OF SCREEN 2 .

SELECTION-SCREEN: BEGIN OF SCREEN 3 AS SUBSCREEN.
PARAMETERS: s_d TYPE d,
            s_t TYPE t.

SELECTION-SCREEN: END OF SCREEN 3 .

SELECTION-SCREEN BEGIN OF TABBED BLOCK tb FOR 10 LINES.
SELECTION-SCREEN TAB (10) tab1 USER-COMMAND tab1_pressed DEFAULT SCREEN 1.
SELECTION-SCREEN TAB (10) tab2 USER-COMMAND tab2_pressed DEFAULT SCREEN 2.
SELECTION-SCREEN TAB (10) tab3 USER-COMMAND tab3_pressed DEFAULT SCREEN 3.
SELECTION-SCREEN END OF BLOCK tb.

INITIALIZATION.
  tab1 = 'Numbers' .
  tab2 = 'Text' .
  tab3 = 'Data and Times' .